### ISSUE TITLE
[import-x/no-duplicates] performance is bad

### ISSUE THREAD

**Issue by tjx666** [un-ts/eslint-plugin-import-x#103]
In most of the files I test, the performance of rule `import-x/no-duplicates` is most bad:

<img width="990" alt="image" src="https://github.com/un-ts/eslint-plugin-import-x/assets/41773861/d074fa82-b8b7-41c1-a19c-2060cc62103a">

test command:

```sh
TIMING=1 eslint /path/to/lint.tsx
```

**Comment by macalinao** [comment]
Having the same issue

**Comment by SukkaW** [comment]
This is expected. `no-duplicates` was ported directly from `eslint-plugin-import` and the code is a messy sh*t. I am going to re-write the rules to be more performant.

**Comment by SukkaW** [comment]
The issue should be resolved and will be released in the next version!
