### ISSUE TITLE
`no-rename-default`

### ISSUE THREAD

**Issue by AndreaPontrandolfo** [un-ts/eslint-plugin-import-x#119]
Any chance of porting [no-rename-default](https://github.com/import-js/eslint-plugin-import/pull/3006) from upstream?

The PR is there but it never got merged (`eslint-plugin-import` is basically abandonware at this point).

**Comment by SukkaW** [comment]
I have been very busy recently. I'm not a full-time open-source contributor and my schedule is packed. But if you want to submit a PR on this, I am more than happy to review it.

**Comment by silverwind** [comment]
It does seem like a useful rule to me.

**Comment by SukkaW** [comment]
@silverwind @AndreaPontrandolfo I've backported the PR in #132. I decided to include this rule in the upcoming `4.1.0` release.
