### ISSUE TITLE
import-x/no-unresolved

### ISSUE THREAD

**Issue by sacru2red** [un-ts/eslint-plugin-import-x#120]
Thanks for good lib

when checking 'import-x/no-unresolved' rules
Can't we evaluate this by taking tsconfig.compilerOptions.path?

![image](https://github.com/user-attachments/assets/f0b109f7-cd85-4f50-bdc1-e3e89e7df73d)

**Comment by error-four-o-four** [comment]
tsconfig paths can be resolved with the corresponding [resolver](https://github.com/import-js/eslint-import-resolver-typescript?tab=readme-ov-file#configuration)

**Comment by sacru2red** [comment]
@error-four-o-four Thanks
