### ISSUE TITLE
Support typescript-eslint@8

### ISSUE THREAD

**Issue by controversial** [un-ts/eslint-plugin-import-x#121]
[typescript-eslint v8 was released last week](https://typescript-eslint.io/blog/announcing-typescript-eslint-v8) with support for eslint@9 and performance + stability upgrades

This repo currently depends on `@typescript-eslint` ^7

**Comment by xsjcTony** [comment]
+1. It's currently not working with the below setup
- eslint-plugin-import-x: v3.1.0
- eslint v9.8.0
- typescript-eslint v8.0.1
- eslint-import-resolver-typescript v3.6.1
```js
settings: {
  'import-x/parsers': {
    '@typescript-eslint/parser': ['.ts', '.tsx', ...vue ? ['.vue'] : []],
   },
  'import-x/resolver': {
    node: {
      extensions: ['.js', '.jsx', '.ts', '.tsx'],
    },
    typescript: true,
  },
}
```
It results in this error
![image](https://github.com/user-attachments/assets/4171c4d4-0a2c-4115-8086-5f12efc8f045)

I'm not sure whether bump typescript-eslint to v8 will help, or some fix is also needed in `eslint-import-resolver-typescript`, but they are just not working together at the moment

**Comment by xsjcTony** [comment]
CC @SukkaW as I can see you worked on both projects

**Comment by filip-be** [comment]
Importing default configs (import-x/recommended + import-x/typescript) breaks with below error message:
![image](https://github.com/user-attachments/assets/a6064c8d-5212-411a-8891-e6836041bd84)

But I have managed to configure the plugin and all rules manually.

My packages:
- @eslint/compat: 1.1.1
- @eslint/eslintrc: 3.1.0
- @eslint/js: 9.8.0
- typescript-eslint: 8.0.1
- eslint: 9.8.0
- eslint-config-prettier: 9.1.0
- eslint-import-resolver-typescript: 3.6.1
- eslint-plugin-import-x: 3.1.0
- eslint-plugin-prettier: 5.2.1
- eslint-plugin-react: 7.35.0

`eslint.config.cjs`:
```tsx
const globals = require('globals');
const js = require('@eslint/js');
const tsEsLint = require('typescript-eslint');
const importX = require('eslint-plugin-import-x');
const react = require('eslint-plugin-react');
const prettier = require('eslint-plugin-prettier/recommended');
const eslint = require('@eslint/js');

module.exports = tsEsLint.config(
  {
    ignores: [
      '**/node_modules',
      '**/build',
      '**/.gitignore',
      '**/.env',
      '**/.env.production',
      '**/.npmrc',
      '**/.prettierrc',
      '**/.prettierrc.js',
      '**/.prettierignore',
      '**/config-overrides.js',
      '**/package-lock.json',
      '**/package.json',
      '**/README.md',
      '**/tsconfig.json',
      '**/eslint.config.cjs',
    ],
  },
  eslint.configs.recommended,
  ...tsEsLint.configs.recommended,
  react.configs.flat.recommended,
  prettier,
  {
    plugins: {
      'import-x': importX,
    },

    languageOptions: {
      globals: {
        ...globals.browser,
      },

      ecmaVersion: 2023,
      sourceType: 'module',

      parserOptions: {
        projectService: true,
        tsconfigRootDir: __dirname,
      },
    },

    settings: {
      'import-x/parsers': {
        '@typescript-eslint/parser': ['**/*.ts', '**/*.tsx'],
      },

      'import-x/resolver': {
        typescript: true,
        node: true,
      },

      react: {
        version: 'detect',
      },
    },

    rules: {
      'react/require-default-props': ['off'],
      '@typescript-eslint/no-use-before-define': ['warn'],

      'no-param-reassign': [
        'error',
        {
          props: false,
        },
      ],
      
      'import-x/no-unresolved': "error",
      'import-x/named': "off",
      'import-x/namespace': "error",
      'import-x/default': "error",
      'import-x/export': "error",
      'import-x/no-named-as-default': "warn",
      'import-x/no-named-as-default-member': "warn",
      'import-x/no-duplicates': "warn",
      'import-x/prefer-default-export': 'error',
      'import-x/no-deprecated': 'warn',
      'import-x/no-extraneous-dependencies': 'error',
      'import-x/no-unused-modules': 'error',
      'import-x/no-absolute-path': 'error',
      'import-x/imports-first': 'error',
      'import-x/newline-after-import': 'error',
      'import-x/no-cycle': 'error',
    },
  }
);
```

**Comment by alaa-paramount** [comment]
> Importing default configs (import-x/recommended + import-x/typescript) breaks with below error message: ![image](https://private-user-images.githubusercontent.com/3452394/355396422-a6064c8d-5212-411a-8891-e6836041bd84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzAxNTAsIm5iZiI6MTcyMzAyOTg1MCwicGF0aCI6Ii8zNDUyMzk0LzM1NTM5NjQyMi1hNjA2NGM4ZC01MjEyLTQxMWEtODg5MS1lNjgzNjA0MWJkODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMTEyNDEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTZmOTdmOTAwYmM0NjNjMmZlNmVlNTJkODhjZTQwZmI3MzdmMmJhMjNkMjcyOWFhNGQ2YTRhZmM0ODVkZWY0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2PPoI_VDpyzL4DpWS570D6mJWZe1Ff45AgkjWxg0XSg)
> 
> But I have managed to configure the plugin and all rules manually.
> 
> My packages:
> 
> * @eslint/compat: 1.1.1
> * @eslint/eslintrc: 3.1.0
> * @eslint/js: 9.8.0
> * typescript-eslint: 8.0.1
> * eslint: 9.8.0
> * eslint-config-prettier: 9.1.0
> * eslint-import-resolver-typescript: 3.6.1
> * eslint-plugin-import-x: 3.1.0
> * eslint-plugin-prettier: 5.2.1
> * eslint-plugin-react: 7.35.0
> 
> `eslint.config.cjs`:
> 
> ```tsx
> const globals = require('globals');
> const js = require('@eslint/js');
> const tsEsLint = require('typescript-eslint');
> const importX = require('eslint-plugin-import-x');
> const react = require('eslint-plugin-react');
> const prettier = require('eslint-plugin-prettier/recommended');
> const eslint = require('@eslint/js');
> 
> module.exports = tsEsLint.config(
>   {
>     ignores: [
>       '**/node_modules',
>       '**/build',
>       '**/.gitignore',
>       '**/.env',
>       '**/.env.production',
>       '**/.npmrc',
>       '**/.prettierrc',
>       '**/.prettierrc.js',
>       '**/.prettierignore',
>       '**/config-overrides.js',
>       '**/package-lock.json',
>       '**/package.json',
>       '**/README.md',
>       '**/tsconfig.json',
>       '**/eslint.config.cjs',
>     ],
>   },
>   eslint.configs.recommended,
>   ...tsEsLint.configs.recommended,
>   react.configs.flat.recommended,
>   prettier,
>   {
>     plugins: {
>       'import-x': importX,
>     },
> 
>     languageOptions: {
>       globals: {
>         ...globals.browser,
>       },
> 
>       ecmaVersion: 2023,
>       sourceType: 'module',
> 
>       parserOptions: {
>         projectService: true,
>         tsconfigRootDir: __dirname,
>       },
>     },
> 
>     settings: {
>       'import-x/parsers': {
>         '@typescript-eslint/parser': ['**/*.ts', '**/*.tsx'],
>       },
> 
>       'import-x/resolver': {
>         typescript: true,
>         node: true,
>       },
> 
>       react: {
>         version: 'detect',
>       },
>     },
> 
>     rules: {
>       'react/require-default-props': ['off'],
>       '@typescript-eslint/no-use-before-define': ['warn'],
> 
>       'no-param-reassign': [
>         'error',
>         {
>           props: false,
>         },
>       ],
>       
>       'import-x/no-unresolved': "error",
>       'import-x/named': "off",
>       'import-x/namespace': "error",
>       'import-x/default': "error",
>       'import-x/export': "error",
>       'import-x/no-named-as-default': "warn",
>       'import-x/no-named-as-default-member': "warn",
>       'import-x/no-duplicates': "warn",
>       'import-x/prefer-default-export': 'error',
>       'import-x/no-deprecated': 'warn',
>       'import-x/no-extraneous-dependencies': 'error',
>       'import-x/no-unused-modules': 'error',
>       'import-x/no-absolute-path': 'error',
>       'import-x/imports-first': 'error',
>       'import-x/newline-after-import': 'error',
>       'import-x/no-cycle': 'error',
>     },
>   }
> );
> ```

it works for me, just add these lines inside your rules object:
...importXPlugin.configs.recommended.rules,
...importXPlugin.configs.typescript.rules,

**Comment by SukkaW** [comment]
https://github.com/un-ts/eslint-plugin-import-x/pull/112#issuecomment-2264466503

> I've decided to postpone the work on this PR. The sheer volume of configurations that need to be migrated without a codemod is overwhelming. I'll focus on backporting [import-js#3018](https://github.com/import-js/eslint-plugin-import/pull/3018) to `eslint-plugin-import-x` instead, which seems to be a more worthwhile task at the moment.
> 
> If anyone would like to take over the PR, please fork my forked repository at [https://github.com/SukkaW/eslint-plugin-import-x/tree/tseslint-v8](https://github.com/SukkaW/eslint-plugin-import-x/tree/tseslint-v8?rgh-link-date=2024-08-02T03%3A45%3A14Z), make changes on the `tseslint-v8` branch, and then submit PRs to my forked repository.

**Comment by controversial** [comment]
#112 is merged!

Once the change is released I’ll test & close this :)

**Comment by nickmessing** [comment]
@controversial what about adding [pkg.pr.new](https://github.com/stackblitz-labs/pkg.pr.new) for testing PRs in scenarios like this?

**Comment by pnodet** [comment]
Any update on what are the blocking points and the roadmap before release? @controversial @SukkaW

**Comment by antfu** [comment]
Before they made the release, I made a fork with the latest commit to workaround this: https://github.com/antfu/eslint-plugin-import-x/tree/fork#readme

**Comment by SukkaW** [comment]
@pnodet @antfu I was waiting for #130 where a util function from typescript-eslint v8 coule be adopted. There is a type mismatch (that can be typed casted). I was going to wait for the typescript-eslint team to fix the typing.

Since it will take time for them to triage the issue, I will merge #130 right now and release a new version.

**Comment by SukkaW** [comment]
#126 is merged, and a new release is under way.

**Comment by SukkaW** [comment]
`eslint-plugin-import-x@4.0.0` is now released with peerDeps of `@typescript-eslint/utils` bumps to 8.

**Comment by antfu** [comment]
Thanks a lot for the release!
