### ISSUE TITLE
`import-x/no-default-export` does not work in typescript

### ISSUE THREAD

**Issue by M-51** [un-ts/eslint-plugin-import-x#144]
Lets say we have simple (flat) config file `eslint.config.js` with only one rule `'import-x/no-default-export': 'error',`
```javascript
import eslintPluginImportX from 'eslint-plugin-import-x'
import tsParser from '@typescript-eslint/parser'

export default [
    {
        files: ['**/*.js'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
        },
        plugins: {
            'import-x': eslintPluginImportX,
        },
        ignores: ['eslint.config.js'],
        rules: {
            'import-x/no-default-export': 'error',
        },
    },
    {
        files: ['**/*.ts'],
        languageOptions: {
            parser: tsParser,
            ecmaVersion: 'latest',
            sourceType: 'module',
        },
        plugins: {
            'import-x': eslintPluginImportX,
        },
        rules: {
            'import-x/no-default-export': 'error',
        },
        settings: {
            'import-x/resolver': {
                typescript: true,
            },
        },
    },
];
```
and two files with identical content:
| `foo.js`  | `foo.ts` |
| ------------- | ------------- |
| <pre>function foo() {<br>    return 'foo';<br>}<br><br>export default foo;</code></pre>  | <pre>function foo() {<br>    return 'foo';<br>}<br><br>export default foo;</pre>  |

eslint shows correctly `'import-x/no-default-export': 'error'` in `foo.js` file
![js](https://github.com/user-attachments/assets/a40a42d4-cf8d-41df-a2a0-adf2cf1be923)

while in `foo.ts` it shows nothing:
![ts](https://github.com/user-attachments/assets/a9caaea6-1bae-4d5c-a6f3-ba32683702e2)

Here is a repo with replicated problem https://github.com/M-51/default-export-bug

---

Worth mentioning, other rules, for example opposite rule - `import-x/prefer-default-export`  works correctly (when added) in the same environment in both JavaScript and Typescript.
![named](https://github.com/user-attachments/assets/f256b09c-4704-4870-a2fd-ecb41a5f7be8)
So it seems, it is only problem with `import-x/no-default-export'`

**Comment by hellpirat** [comment]
Yeah I got the same error

**Comment by jleider** [comment]
Just ran into this issue yesterday as well after converting from the forked import plugin to import-x.

**Comment by SukkaW** [comment]
@hellpirat @jleider @M-51 

I am to re-produce the issue w/ the minimum re-production, but I can't re-produce within the unit test cases.

**Comment by SukkaW** [comment]
Update: I am to locate the issue, I will create a PR fixing this.
