### ISSUE TITLE
import-x/resolver settings syntax

### ISSUE THREAD

**Issue by AaronPorts** [un-ts/eslint-plugin-import-x#153]
I'm using eslint-import-resolver-oxc and it seems `"import-x/resolver": "oxc"` doesn't work, firing `Unable to resolve path to module`, while `"import-x/resolver": { oxc: true }` works as expected.

```javascript
languageOptions: {
  parser: typescriptParser,
  sourceType: "module",
  parserOptions: {
    ecmaVersion: "latest",
    projectService: true,
    tsconfigRootDir: import.meta.dirname,
  },
},
settings: {
  "import-x/parsers": { "@typescript-eslint/parser": [".ts", ".tsx"] },
  "import-x/resolver": { oxc: true },
},
```

**Comment by vladshcherbin** [comment]
This one worked for with just `'oxc'` using latest versions so it might be fixed. The new resolver syntax obsoletes this issue anyway.
