### ISSUE TITLE
How to configure import-x/extensions to enforce .js

### ISSUE THREAD

**Issue by bodinsamuel** [un-ts/eslint-plugin-import-x#164]
Hi,

I recently switched from eslint-plugin-import to this package, thanks for taking over. 
Most things are drop-in replacements but I'm struggling with `import-x/extensions` in Typescript env.

No matter what I'm configuring it's always asking to add `.ts` extension, while it works with bun and bundler, it's not correct when targeting node. Is there a way to configure it to ask for `.js`? Or did I misconfigure something?

```ts
 'import-x/extensions': [
    'error',
    'always',
      {
          json: 'always',
          js: 'always',
          ts: 'never',
          ignorePackages: true,
     },
 ],
```

Thanks in advance

**Comment by SukkaW** [comment]
I myself never use the `.js` extension. But your use case seems simple enough and you don't have to use `import-x/extensions`.

`typescript-eslint` docs have provided a way to use the `no-restricted-syntax` rule to enforce the `.js` extension: https://typescript-eslint.io/troubleshooting/typed-linting/performance/#importextensions-enforcing-extensions-are-used

**Comment by SukkaW** [comment]
Closes as stale.

**Comment by doubleaxe** [comment]
For anyone coming here with the same question - use `eslint-plugin-n/file-extension-in-import` rule, it supports checking ts and js files, and supports js extension for ts files.

[https://github.com/eslint-community/eslint-plugin-n/](https://github.com/eslint-community/eslint-plugin-n/)
