### ISSUE TITLE
How to resolve exports from gts files as imports in ts files to prevent import-x/no-unresolved

### ISSUE THREAD

**Issue by tojofo** [un-ts/eslint-plugin-import-x#173]
Hi, we have an Ember app written in TypeScript.  We use the import-x plugin and the new eslint flat file config and everything has been working fine. We have updated our app to use the [Ember Template Tag format](https://guides.emberjs.com/release/components/template-tag-format/#toc_class-based-components) and since then a pure TypeScript file in say the `app/lib` folder cannot resolve an import from a component in `.gts` format.

Example code;
```
// appname/app/components/app/animation-dropdown/index.gts
export interface AnimationOptions {
  [key: string]: AnimationOption;
}

// appname/app/lib/timeline/element.ts
import type { AnimationOptions } from "client/components/app/animation-dropdown/";  // errors in linting with import-x/no-unresolved
```

I have tried various incantations of resolving and parsers and what not but nothing has worked.
What is a configuration in `settings: {}` that should in theory at least work and have `import-x` resolve the imports?

I have seen conversation in a different thread about dropping the concept of resolvers which makes me think what I am trying to do should work?

Here is an example snippet from our `eslint.config.mjs`

```
import globals from "globals";
import eslint from "@eslint/js";
import eslintPluginEmber from "eslint-plugin-ember";
import eslintPluginEmberRecommended from "eslint-plugin-ember/configs/recommended";
import eslintPluginImportX from "eslint-plugin-import-x";
import typescriptEslint from "typescript-eslint";
import eslintPluginPrettier from "eslint-plugin-prettier";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";
import eslintNode from "eslint-plugin-n";
import emberEslintParser from "ember-eslint-parser";

export default [
  eslint.configs.recommended,
  ...eslintPluginEmberRecommended,
  eslintPluginPrettierRecommended,
  eslintPluginImportX.flatConfigs.recommended,
  eslintPluginImportX.flatConfigs.typescript,
  {
    files: ["**/*.ts"],
    plugins: {
      ember: eslintPluginEmber,
      "@typescript-eslint": typescriptEslint.plugin,
      prettier: eslintPluginPrettier,
      import: eslintPluginImportX
    },
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node
      },
      parser: typescriptEslint.parser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
        projectService: true,
        tsconfigRootDir: import.meta.dirname
      }
    },
    settings: {
      "import-x/extensions": [".ts", ".gts", ".js", ".cjs", ".mjs"],
      "import-x/parsers": {
        "@typescript-eslint/parser": [".gts"]
      },
      "import-x/resolver": {
        typescript: {
          alwaysTryTypes: true
        },
        node: {
          extensions: [".js", ".ts"],
          moduleDirectory: ["node_modules", "app"]
        }
      }
    }
  }
]
```

Based on snippets around the web about the various plugins etc I have tried various incantations of parsers, eg setting the configuration parser to the `emberEslintParser` or using that in settings like;
```
"import-x/parsers": {
  "ember-eslint-parser": [".gts"]
}
```

But nothing seems to make import-x scan .gts files for exports.

Is it possible?
What might a configuration look like?

**Comment by JounQin** [comment]
Please try https://github.com/import-js/eslint-import-resolver-typescript?tab=readme-ov-file#extensions

**Comment by tojofo** [comment]
Thank you I have already tried;

```
settings: {
  "import-x/extensions": [".ts", ".gts"]
}
```

and it did not work.

Should the setting be `extensions` or `"import-x/extensions"`?

**Comment by JounQin** [comment]
It's not `import-x/extensions` setting, it's `eslint-import-resolver-typescript`'s option, they are different.

**Comment by SukkaW** [comment]
`eslint-import-resolver-typescript` should be able to resolve ember template files. Closing.
