### ISSUE TITLE
Some problem with the "restrictions" option

### ISSUE THREAD

**Issue by Perfectoff** [un-ts/eslint-plugin-import-x#178]
Here is the configuration:

```
const tsResolver= require('eslint-import-resolver-typescript');

module.exports = {
    root: true,
    parser: "@typescript-eslint/parser",
    parserOptions: {
        project: "./tsconfig.json",
        tsconfigRootDir: ".",
        sourceType: "module",
    },
    plugins: [
        "@typescript-eslint",
        "import-x"
    ],
    extends: [
        "plugin:import-x/typescript",
    ],
    rules: {
        "import-x/no-unresolved": "error"
    },
    settings: {
        "import-x/resolver": {
            name: 'tsResolver',
            options: {
                restrictions: [/.*/]
            },
            resolver: tsResolver,
            typescript: true,
            node: true
        }
    }
}
```

The "restrictions" option here specifies a regular expression that resolves any pattern. However, eslint reports an error on every import.

I decided to check what data comes to the resolver:

```
...
resolver: {
    ...tsResolver,
    resolve: (...args)=>{
        log(args);   // output: [importName, sourceFileName, { "restrictions": [someObject] }]
        log(args[2]["restrictions"] instanceof RegExp);  // output: false
        let res= tsResolver.resolve(...args); 
        log(res);  // output: {"found": false} 
        return res;
    }
},
```

As you can see, the value in "restrictions" is no longer a RegExp, but is replaced by some other object. And as a result, resolve fails.
If you replace this value with the original expression
`args[2]= { restrictions: /.*/ };`
then everything works fine.

**Comment by SukkaW** [comment]
There is no `restrictions` option, neither in `eslint-plugin-import-x` nor in `eslint-import-resolver-typescript`.

**Comment by Perfectoff** [comment]
> There is no `restrictions` option, neither in `eslint-plugin-import-x` nor in `eslint-import-resolver-typescript`.

In the description of `eslint-import-resolver-typescript` there is an [option section](https://github.com/import-js/eslint-import-resolver-typescript?tab=readme-ov-file#other-options) which says:

> You can pass through other options of [enhanced-resolve](https://github.com/webpack/enhanced-resolve) directly

And these options include 'restrictions':

![2024-11-16_04-54-37](https://github.com/user-attachments/assets/7b9a83a3-ffbd-4665-a7cd-8763fd434e42)



So I pass it correctly.
