### ISSUE TITLE
Missing doctrine types

### ISSUE THREAD

**Issue by voxpelli** [un-ts/eslint-plugin-import-x#197]
I'm getting this typescript error when I'm importing the latest `v4.5.0` version of this module: https://github.com/voxpelli/eslint-config/pull/388

> Error: `node_modules/eslint-plugin-import-x/lib/utils/export-map.d.ts(2,33)`:

> error TS7016: Could not find a declaration file for module `doctrine`. `node_modules/eslint-plugin-import-x/node_modules/doctrine/lib/doctrine.js` implicitly has an `any` type.

Can you do what TypeScript suggests?

> Try `npm i --save-dev @types/doctrine` if it exists or add a new declaration (.d.ts) file containing `declare module 'doctrine';`

I searched for previous issues on the same subject, but did not find any, hence why I'm filing a new issue. Sorry for making it somewhat short, if you want / need more data then ask and I can try to fulfill those needs.

**Comment by SukkaW** [comment]
Including `@types/doctrine` in the `dependencies` of `eslint-plugin-import-x` should fix the issue! Would you like to send a PR?
