### ISSUE TITLE
Replacing the built-in default import resolver that supports `exports` and `imports` from `package.json`

### ISSUE THREAD

**Issue by SukkaW** [un-ts/eslint-plugin-import-x#208]
`eslint-plugin-import-x` has `eslint-import-resolver-node` as a dependency. When no resolver is specified in the eslint config, the `eslint-import-resolver-node` will be used. However, `eslint-import-resolver-node` doesn't support `exports` and `imports` from `package.json` and @ljharb ~~simply refuses~~ doesn't have time to implement this feature and even locks the feature request issue, see https://github.com/import-js/eslint-plugin-import/issues/1810.

So our plan is to abandon the `eslint-import-resolver-node`. We will be building a new eslint import resolver upon ~~[`@dual-bundle/import-meta-resolve`](https://www.npmjs.com/package/@dual-bundle/import-meta-resolve)~~ [`enhanced-resolve`](https://www.npmjs.com/package/enhanced-resolve). We will ship it with `eslint-plugin-import-x` and it will be an interface v3-only resolver.

In the next major version of `eslint-plugin-import-x`, we will remove `eslint-import-resolver-node` in favor of our own default resolver.

**Comment by SukkaW** [comment]
Note that the default resolver will try to match the Node.js resolving behavior, so no `jsconfig.json` or `tsconfig.json` support. Anyone interested in those should checkout `eslint-import-resolver-typescript`, `eslint-import-resolver-oxc`, or `eslint-import-resolver-next` (which is also based on oxc).

**Comment by ljharb** [comment]
To be clear, i certainly don’t refuse to implement the feature; it’s that to do it properly takes more time than I’ve had yet (and can’t be done with only require.resolve/import.meta.reaolve, because people frequently need to lint for node versions different from the one they’re running)

**Comment by SukkaW** [comment]
> Why not use `import.meta.resolve` for the node resolver? Is it because it's synchronous only?

Yes. The resolving happens inside the ESLint plugin, and the ESLint plugin needs to be synchronous. Besides `import.meta.resolve` only exists in ESM while both `eslint-plugin-import-x` and `eslint-plugin-import` have many users working with CJS.

**Comment by JounQin** [comment]
All done in https://github.com/un-ts/eslint-plugin-import-x/releases/tag/v4.14.0

**Comment by UrkelMoeDee** [comment]
Pardon me if I'm missing something, but if I'm using v4.16.1, are there any additional settings I need to add to allow eslint-plugin-import-x to recognize my package.json `imports`? I'm currently seeing `import-x/no-unresolved` errors for my `imports` aliases.

# Example:
## package.json
```json
{
    ...
    "imports": {
        "#alias-name": {
            "test": "./some/local-file.js",
            "default": "external-package"
        }
    },
    ...
}
```

## Error
`error  Unable to resolve path to module '#alias-name'              import-x/no-unresolved`

**Comment by JounQin** [comment]
Please raise a new issue with minimal reproduction instead.
