### ISSUE TITLE
Support ESLint v9.0

### ISSUE THREAD

**Issue by antfu** [un-ts/eslint-plugin-import-x#60]
The context interface has changed, and removed in v9.0. For example: https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#context.getscope()

This plugin on ESLint v9.0.0-rc.0 will throw errors like: 
<img width="1127" alt="image" src="https://github.com/un-ts/eslint-plugin-import-x/assets/11247099/0c857a9f-d563-42e3-8cdb-ef1e6b9f2952">

I tried to check the codebase, but it seems the overall dependencies of this repo are still a bit left behind. Like `@typescript-eslint/utils` is still v5 while now it's v7 - some the we don't even have the compact types for the new APIs - I wonder what's the strategies of this repo, should we keep support eslint v7 and v8, or we could do a major that only support latest v8.40+ + v9?

**Comment by SukkaW** [comment]
> I tried to check the codebase, but it seems the overall dependencies of this repo are still a bit left behind. Like `@typescript-eslint/utils` is still v5 while now it's v7
 
I've already attempted that yesterday. I tried to upgrade `ts-eslint/utils` from version 5 to version 6 but was unsuccessful. The migration needs to change tons of stuff.

**Comment by JounQin** [comment]
I'm personally fine with dropping legacy eslint versions, but https://github.com/ota-meshi/eslint-compat-utils can also be considered at the same time.

And also I want to upgrade tseslint related packages first, as @SukkaW described, it's not that easy, we need to adapt some rules internally.

**Comment by JounQin** [comment]
Please help to test eslint-plugin-import-x@0.4.2

**Comment by JounQin** [comment]
@SukkaW See #66

**Comment by Zxilly** [comment]
I noticed import-x still depends on `@typescript-eslint/utils` at version `^7.4.0`, should we bump it to `8.0.0-alpha.39` to remove the recersive depends on eslint v8?

**Comment by GaborTorma** [comment]
`@typescript-eslint/utils` now stable of v8. Please bump it.

**Comment by pavitra-infocusp** [comment]
Agreed @GaborTorma 

```
 WARN  Issues with peer dependencies found
.
└─┬ @antfu/eslint-config 2.24.1
  └─┬ eslint-plugin-import-x 3.1.0
    └─┬ @typescript-eslint/utils 7.18.0
      └── ✕ unmet peer eslint@^8.56.0: found 9.8.0
```
