### ISSUE TITLE
Dependency strategy

### ISSUE THREAD

**Issue by JounQin** [un-ts/eslint-plugin-import-x#69]
I'm still unsure whether to merge #66 as-is, that PR removes eslint v7 support, it is of course good to keep dependencies clean and updated, but it seems there are still many eslint v7 users.

<img width="778" alt="image" src="https://github.com/un-ts/eslint-plugin-import-x/assets/8336744/f357ce58-9721-4c28-b42d-aa1db7391208">

On the other hand, eslint v9 is a big major version, it removes legacy `RuleTester` class and made previous `FlatRuleTester` as now `RuleTester`, so it's difficult to test eslint v9- versions and v9+ at the same time. Maybe we can use something like `"eslint9": "npm:eslint^9.0.0-rc.0"` to test flat config only for eslint v9.

For `@typescript-eslint/utils`, I don't know how many efforts it would take to support both `v6` and `v7` for eslint v7.

However, the last version of eslint v7 was released 3 years ago, maybe we should just consider it as legacy and drop its support.

cc @SukkaW @antfu

**Comment by zloirock** [comment]
I don't think that the overwhelming majority of ESLint 7 users update their plugins. I think that it's better to drop its support.

**Comment by antfu** [comment]
From my point of view, since this project is supposed to be the "modern fork" of eslint-plugin-import, I would personally expect it to be up-to-date with lean and efficient code as possible. Giving v7 is already 3 years ago, I would vote to drop the support as well.

**Comment by SukkaW** [comment]
Let's support down to ESLint 8.56.0 then.

**Comment by silverwind** [comment]
Definitely drop v7 support. I'd even go as far as saying drop v8 soon after v9 release when everyone will be moving their configs to flat format.

**Comment by SukkaW** [comment]
> Definitely drop v7 support. I'd even go as far as saying drop v8 soon after v9 release when everyone will be moving their configs to flat format.

Let's keep ESLint v8 support, but only down to the 8.40.0 (or even 8.56.0). ESLint 8.40.0 is where the context properties were added and ESLint 8.56.0 is currently the most popular ESLint v8 version.

**Comment by JounQin** [comment]
Indeed, we are going to be a __"modern fork"__, I've changed to request `eslint>=8.56.0` at #66
