### ISSUE TITLE
Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by wojtekmaj** [un-ts/eslint-plugin-import-x#73]
It appears that the source code requires `tslib`:

`node_modules/eslint-plugin-import-x/lib/index.js`

```js
"use strict";
const tslib_1 = require("tslib");
const electron_1 = tslib_1.__importDefault(require("./config/electron"));
const errors_1 = tslib_1.__importDefault(require("./config/errors"));
const react_1 = tslib_1.__importDefault(require("./config/react"));
// …
```

but the package does not declare it in its dependencies. This causes the error if tslib has not been already installed by another package, and in Yarn PnP, unconditionally.

**Comment by karlhorky** [comment]
I'm able to confirm this also with pnpm - I experienced this today in one of our projects using `eslint-plugin-import-x`

@JounQin what do you think about this one? Should `tslib` be added as a dependency?

**Comment by danciudev** [comment]
Same problem with pnpm and bun.

**Comment by JounQin** [comment]
Oh, it should be listed as dep, PR welcome.

**Comment by unzico** [comment]
> Oh, it should be listed as dep, PR welcome.

Opened a PR: https://github.com/un-ts/eslint-plugin-import-x/pull/82
