### ISSUE TITLE
What does `settings."import-x/resolver".typescript: true` do ?

### ISSUE THREAD

**Issue by Samuel-Therrien-Beslogic** [un-ts/eslint-plugin-import-x#77]
https://github.com/un-ts/eslint-plugin-import-x#typescript suggests doing (translated to js/json):
```js
"settings": {
  "import-x/resolver": {
    "typescript": true
  }
}
```

but also links to https://github.com/import-js/eslint-import-resolver-typescript#configuration which tells me to do (after changing `import/` to `import-x/`:
```js
"settings": {
  "import-x/parsers": { // Updated to import-x
    "@typescript-eslint/parser": [".ts", ".tsx"]
  },
  "import-x/resolver": { // Updated to import-x
    "typescript": {
      "alwaysTryTypes": true,
      "project": [ // I'm using my @typescript-eslint/parser projects configs for this example
          "tsconfig?(.*).json",
          // From our Angular preset
          "projects/*/tsconfig?(.*).json",
          "*/tsconfig?(.*).json" // For example: e2e/tsconfig.json
        ]
    }
  }
}
```

It is unclear to me what `"typescript": true` does and why it differs from the linked documentation.

**Comment by JounQin** [comment]
It's same as `typescript: {}` which use default options for the resolver.
