### ISSUE TITLE
Port `ignoreUnusedTypeExports` option of `no-unused-modules`

### ISSUE THREAD

**Issue by silverwind** [un-ts/eslint-plugin-import-x#86]
I'm willing to port https://github.com/import-js/eslint-plugin-import/pull/3011 into this module, it's a useful option to have.

**Comment by SukkaW** [comment]
@silverwind Sure! Please do. It is indeed a great option.

**Comment by silverwind** [comment]
Waiting a bit more for that PR to review/merge.

**Comment by SukkaW** [comment]
@silverwind You can backport here first since I can review PR quicker and more frequently. The test infra here is better as well.

**Comment by silverwind** [comment]
I have decided to disable `no-unused-modules` in my configs, so I'm sorry but I'm no longer interested in porting it.

**Comment by silverwind** [comment]
Actually I gave it a second thought and would enable that rule again if `ignoreUnusedTypeExports` is supported, so here is the port:

https://github.com/un-ts/eslint-plugin-import-x/pull/116
