### ISSUE TITLE
CI failed and v0.5.1 was not published

### ISSUE THREAD

**Issue by teppeis** [un-ts/eslint-plugin-import-x#88]
From [CI#217](https://github.com/un-ts/eslint-plugin-import-x/actions/runs/8557755984), CI failed.
[v0.5.1](https://github.com/un-ts/eslint-plugin-import-x/commit/3abe5e49683e0f973232bb631814b935e1ca7091) was not published.

I don't know if this is the cause, but on ubuntu-22.04 with image version 20240403.1.0 or later, the node v16 job is failing to find yarn.

**Comment by SunsetTechuila** [comment]
> From [CI#217](https://github.com/un-ts/eslint-plugin-import-x/actions/runs/8557755984), CI failed.

this a lint action that was triggered by the pull request, it has nothing to do with releases 

> [v0.5.1](https://github.com/un-ts/eslint-plugin-import-x/commit/3abe5e49683e0f973232bb631814b935e1ca7091) was not published.

it was - https://www.npmjs.com/package/eslint-plugin-import-x/v/0.5.1

> I don't know if this is the cause, but on ubuntu-22.04 with image version 20240403.1.0 or later, the node v16 job is failing to find yarn.

not related to this repo at all, see https://github.com/actions/setup-node/issues/1075

**Comment by SukkaW** [comment]
It seems that Node.js 16's corepack can't install yarn. I don't know why though, but I am going to work on it.

**Comment by SunsetTechuila** [comment]
> Node.js 16's corepack can't install yarn.

No, the latest Corepack can't fetch anything because it tries to use Node's built-in fetch, which was only added in Node v18. Why is the latest Corepack being used? Because `corepack enable` is run before setting up Node.

> I am going to work on it.

The only solution: https://github.com/actions/setup-node/issues/1075#issuecomment-2165643488

**Comment by SukkaW** [comment]
@SunsetTechuila

Thanks for providing so many details and context!

Would you like to create a PR to help us fix the CI?

**Comment by SunsetTechuila** [comment]
@SukkaW done

**Comment by teppeis** [comment]
Thank you!
