### ISSUE TITLE
support for `exports`

### ISSUE THREAD

**Issue by benmccann** [un-ts/eslint-plugin-import-x#9]
A major issue with `eslint-plugin-import` is that it doesn't support `exports`: https://github.com/import-js/eslint-plugin-import/issues/1810

I was wondering if you might consider using `resolve.exports` or `enhanced-resolve` rather than the outdated `resolve` package in this library to address that

**Comment by JounQin** [comment]
If you're using TypeScript, you can use `eslint-import-resolver-typescript`, for plain js, it doesn't support it for now, but I think your suggestion is valuable, I'll try to add this feature this weekend.

**Comment by JounQin** [comment]
@benmccann Another thought, did you just try eslint-import-resolver-exports? So that less change could be made in this fork.

**Comment by benmccann** [comment]
It's rather complicated to setup. It requires another package as well, so you have to setup at least three libraries for something that seems like it should really just work out of the box.

I understand wanting to keep the diff to upstream small as well though. I do think it would affect adoption a lot though to use `eslint-import-resolver-exports`. It would be really nice if the migration instructions were simply to switch `eslint-plugin-import` to `eslint-plugin-i` vs something more complicated.

**Comment by benmccann** [comment]
That's exactly what we were just talking about in the last comment

**Comment by 13OnTheCode** [comment]
By the way, the latest version of VSCode currently does not support `exports`, so you still cannot completely get rid of the `main` field. I also want to fully embrace ESM, but unfortunately, we were born in the worst era for it.

**Comment by JounQin** [comment]
I think this is outscoped, you should use `eslint-import-resolver-exports` or `eslint-import-resolver-typescript` instead.

**Comment by benmccann** [comment]
I personally have just stopped using `eslint-plugin-imports` altogether as it provides no value that isn't already provided by Typescript. Unfortunately many others still use it and then end up bugging me that my libraries are not working with their outdated plugin. Unfortunately, I can't ask everyone to use one of the resolver plugins because they're far too cumbersome to setup. C'est la vie!

**Comment by ljharb** [comment]
That's definitely not accurate - there's a ton of things it does that TS can't - but it's unfortunate that's been your experience.

**Comment by JounQin** [comment]
`eslint-import-resolver-typescript` works without `typescript` itself, that's why we're using `get-tsconfig` instead of relying on `typescript` because it's heavily for non typings.

**Comment by SukkaW** [comment]
For those who are interested in this, please check https://github.com/un-ts/eslint-plugin-import-x/issues/208.
