### ISSUE TITLE
`Unable to resolve path to module` on `bun` or modules with `bun:` prefix

### ISSUE THREAD

**Issue by karlhorky** [un-ts/eslint-plugin-import-x#92]
Importing modules with `bun:` prefix (eg. [`bun:test`](https://bun.sh/docs/cli/test#run-tests)) or `bun` itself with [`@types/bun`](https://www.npmjs.com/package/@types/bun) installed results in a resolution error with [`import-x/no-unresolved`](https://github.com/un-ts/eslint-plugin-import-x/blob/master/docs/rules/no-unresolved.md)

```
Unable to resolve path to module 'bun:test'. eslint import-x/no-unresolved
```

`index.test.ts`

```ts
import { expect, test } from 'bun:test';

test('2 + 2', () => {
  expect(2 + 2).toBe(4);
});
```

![Screenshot 2024-06-14 at 16 42 13](https://github.com/un-ts/eslint-plugin-import-x/assets/1935696/2c04bf4d-2d3d-42cf-bc99-6089d68bf47d)

**Comment by karlhorky** [comment]
## Configuration Solution / Workaround

If automating this based on the TS types in [`@types/bun`](https://www.npmjs.com/package/@types/bun) is not possible / feasible / wanted, then one way that I've found to work around this is to use [the `ignore` option](https://github.com/un-ts/eslint-plugin-import-x/blob/master/docs/rules/no-unresolved.md#ignore):

```diff
import eslintTypescript from '@typescript-eslint/eslint-plugin';
import typescriptParser from '@typescript-eslint/parser';
import eslintImportX from 'eslint-plugin-import-x';
import globals from 'globals';

/** @type
 * {import('@typescript-eslint/utils/ts-eslint').FlatConfig.ConfigArray}
 * */
const configArray = [
  {
    // Lint common extensions by default with rules above
    files: [
      '**/*.js',
      '**/*.jsx',
      '**/*.cjs',
      '**/*.mjs',
      '**/*.ts',
      '**/*.tsx',
      '**/*.cts',
      '**/*.mts',
    ],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        project: './tsconfig.json',
        // typescript-eslint specific options
        warnOnUnsupportedTypeScriptVersion: true,
      },
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.commonjs,
        ...globals.es2021,
        // Allow using React as a global without importing it
        React: true,
      },
    },
    plugins: {
      '@typescript-eslint': {
        rules: eslintTypescript.rules,
      },
      'import-x': eslintImportX,
    },
    settings: {
      'import-x/parsers': {
        '@typescript-eslint/parser': ['.ts', '.tsx'],
      },
      'import-x/resolver': {
        // Load <rootdir>/tsconfig.json
        typescript: true,
        node: true,
      },
    },
    rules: {
      // Error on imports that don't match the underlying file
      // system
      // https://github.com/un-ts/eslint-plugin-import-x/blob/master/docs/rules/no-unresolved.md
      'import-x/no-unresolved':
-        'error',
+        [
+          'error',
+          {
+            ignore: ['^bun:\\w+$'],
+          },
+        ],
    },
  },
];


export default configArray;
```

**Comment by SukkaW** [comment]
See also https://github.com/import-js/eslint-import-resolver-typescript/pull/266

**Comment by SukkaW** [comment]
```ts
import { isBuiltin } from 'node:module'

console.log(isBuiltin('bun:sqlite'))
// In Node.js: false
// In Bun: true
```

Thus we can't use `isBuiltin` here as ESLint might still be running under Node.js rather than Bun (E.g. in IDE).

**Comment by karlhorky** [comment]
Ah just saw this other PR:

- https://github.com/import-js/eslint-import-resolver-typescript/pull/288

I guess once this is published and `eslint-plugin-import-x` upgrades to it, it will resolve the issue

**Comment by SukkaW** [comment]
The latest version of `eslint-import-resolver-typescript` should have fixed the issue.

**Comment by karlhorky** [comment]
@SukkaW thanks for the heads up!

Yeah indeed, I can confirm that [`eslint-import-resolver-typescript@3.6.3`](https://github.com/import-js/eslint-import-resolver-typescript/releases/tag/v3.6.3) resolves the issue 🎉

Relevant PR from @SunsetTechuila :

- https://github.com/import-js/eslint-import-resolver-typescript/pull/288

This uses the new [`is-bun-module`](https://www.npmjs.com/package/is-bun-module) package ([GitHub](https://github.com/SunsetTechuila/is-bun-module)), nice 👀

**Comment by karlhorky** [comment]
Ah, just upgraded dependencies and received `Unable to resolve path to module 'bun:test'` from `import-x/no-unresolved` again:

```bash
$ yarn eslint . --max-warnings 0
$ /home/runner/work/courses/courses/node_modules/.bin/eslint . --max-warnings 0
/home/runner/work/courses/courses/packages/curriculum-versions/curriculumVersions/2024-3-fall-pern-extensive-eu/drone/__tests__/smokeTest.test.ts
Error:   2:30  error  Unable to resolve path to module 'bun:test'  import-x/no-unresolved
/home/runner/work/courses/courses/packages/curriculum-versions/curriculumVersions/2025-1-winter-pern-extensive-eu/drone/__tests__/smokeTest.test.ts
Error:   2:30  error  Unable to resolve path to module 'bun:test'  import-x/no-unresolved
/home/runner/work/courses/courses/packages/fusion.upleveled.io/__tests__/smokeTestDevServer.test.ts
Error:   6:30  error  Unable to resolve path to module 'bun:test'  import-x/no-unresolved
/home/runner/work/courses/courses/packages/learn.upleveled.io/__tests__/smokeTestDevServer.test.ts
Error:   6:30  error  Unable to resolve path to module 'bun:test'  import-x/no-unresolved
```

Looking into the last dependency changes, it appears that [`eslint-import-resolver-typescript@4.2.0`](https://github.com/import-js/eslint-import-resolver-typescript/releases/tag/v4.2.0) caused this change:

> ## Minor Changes
> - https://github.com/import-js/eslint-import-resolver-typescript/pull/391 [c8121e5](https://github.com/import-js/eslint-import-resolver-typescript/commit/c8121e5eb4ce25a79396ae75df16d35fc67acbc6) Thanks [@JounQin](https://github.com/JounQin)! - feat: make is-bun-module as optional peer dependency
>
> Technically this is a BREAKING CHANGE, but considering we just raise out v4 recently and this only affects bun users, bun --bun eslint even works without this dependency, so I'd consider this as a minor change.
>
> So for bun users, there are three options:
> 
> 1. install `is-bun-module` dependency manually and use `bun: true` option
> 2. run `eslint` with `bun --bun eslint` w/o `bun: true` option
> 3. enable `run#bun` in [bunfig.toml](https://bun.sh/docs/runtime/bunfig#run-bun-auto-alias-node-to-bun) w/o `bun: true` option

@JounQin @SukkaW should this be added to the readme of `eslint-plugin-import-x`?

**Comment by JounQin** [comment]
No change needed in `eslint-plugin-import-x`.

Did you enable `bun: true` option for `eslint-import-resolver-typescript`? Or just try `bun --bun eslint`?

**Comment by karlhorky** [comment]
Ah yeah, I forgot that [I configured `import-x/resolver` in my shared config](https://github.com/upleveled/eslint-config-upleveled/blob/f3667b211140e60899b0f52802ed208b83173314/index.js#L536-L540).

I'll take a look at:

1. Reconfiguring this in `eslint-config-upleveled`
2. Updating the readme for the `import-x/resolver` config

**Comment by karlhorky** [comment]
> I'd recommend using `import-x/resolver-next` when possible for flat config.

Nice, this looks great! I'll wait until it's not marked `next` anymore to upgrade.
