### ISSUE TITLE
feature: `prefer-node-protocol`

### ISSUE THREAD

**Issue by benmccann** [un-ts/eslint-plugin-import-x#96]
We're using `eslint-plugin-unicorn` for a single rule that would make sense to have in this plugin:
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-node-protocol.md

I'd love to switch to this plugin since it has half as many dependencies. See https://npmgraph.js.org/?q=eslint-plugin-unicorn vs https://npmgraph.js.org/?q=eslint-plugin-import-x (and maybe we could cut it in half again if removing `globby` from `@typescript-eslint/typescript-estree`)

**Comment by benmccann** [comment]
It should also be noted that this rule is highly requested in the `eslint-plugin-import` repo: https://github.com/import-js/eslint-plugin-import/issues/2717

**Comment by benmccann** [comment]
It would be nice to use `module.isBuiltin` for this, but that would be a breaking change as it got added in node 16.17.0 and 18.6.0 (https://github.com/npm/normalize-package-data/pull/224)

**Comment by benmccann** [comment]
There's already a `no-nodejs-modules` rule. I guess this should have somewhat similar code

**Comment by SukkaW** [comment]
I also hate loads of transitive dependencies `eslint-plugin-unicorn` is introducing.

But I notice that the `prefer-node-protocol` rule is also available in the `eslint-plugin-n`: https://github.com/eslint-community/eslint-plugin-n/blob/master/lib/rules/prefer-node-protocol.js and it is also a lightweight eslint plugin with rules specific designed for Node.js.

**Comment by SukkaW** [comment]
As for the `globby` inside `@typescript-eslint/estree`, I've created a proposal here: https://github.com/typescript-eslint/typescript-eslint/issues/9453. Please vote on the proposal!

**Comment by benmccann** [comment]
Oh, wow! I wish I knew about that earlier :laughing: Thanks for letting me know!

Okay, closing in favor of: https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/prefer-node-protocol.md
